### ISSUE TITLE
A question regarding load times

### ISSUE THREAD

**Issue by thebestcoderofcourse** [YANBForwarder/YANBF#24]
Hello YANBF Developer team. I hope you are well. I would love to use your forwarding software but was wondering if there would be any latency differences? does running it through 3ds mode effect any loading times? I know TwighlightMenu++ Has the drive which indicates game (listed below). Are the differences the same?

differences(https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/htmlview#gid=0)

Is it also compatible with TWPatch screen scaler? 

Thank you again for your time.

**Comment by lifehackerhansol** [comment]
All the 3DS mode does is add an extra step to the original DSiWare-based forwarders.

Crash course on how DSiWare forwarders work:
1. You launch the forwarder
2. The forwarder is a DS-mode title, so the 3DS automatically reboots into DS mode, then loads the forwarder title
3. The forwarder then loads the SD-side bootloader which sets the necessary arguments
4. SD-side bootloader launches nds-bootstrap
5. nds-bootstrap launches game

What I did, is this:
1. You launch the forwarder
2. The forwarder is a 3DS-mode title, so the 3DS directly boots the title
3. The forwarder will launch the `bootstrap.cia` file you installed, which is a DS-mode title, so the 3DS reboots into DS mode.
    - `bootstrap.cia` is just a subsidized version of the DSiWare forwarder icon, hidden from the HOME menu but effectively does the same thing
4. Do steps 3-5 in the DSiWare forwarder steps

So at the end, it is still in DS-mode for the actual game playback, so your experience as to gaming will be identical. The load time will be a tad bit longer though due to all the rebooting crap that we need to do.

Since TWiLight Menu++, the DSiWare forwarders and YANBF all use nds-bootstrap for everything, said compatibility list will be identical across all three provided you continually update nds-bootstrap. The same will go for TWPatch, which affects DS-mode in its entirety, and since we end up in DS mode it will launch with the TWPatch'd filters/scalers etc.

Thank you for using YANBF, hope this helps.
